import { MnsWorldModule } from "@/types";

export const APP_MODULES: MnsWorldModule[] = [
  {
    id: "career",
    route: "/career",
    titleKey: "modules.career.title",
    descriptionKey: "modules.career.desc",
    icon: "Compass",
    badge: "Super Module",
    enabled: true,
  },
  {
    id: "life-goals",
    route: "/life-goals",
    titleKey: "modules.goals.title",
    descriptionKey: "modules.goals.desc",
    icon: "Target",
    badge: "Direction & Habits",
    enabled: true,
  },
  {
    id: "enjoy",
    route: "/enjoy",
    titleKey: "modules.enjoy.title",
    descriptionKey: "modules.enjoy.desc",
    icon: "Sparkles",
    badge: "118 Quests & Media",
    enabled: true,
  },
  {
    id: "web-hub",
    route: "/web-hub",
    titleKey: "modules.webHub.title",
    descriptionKey: "modules.webHub.desc",
    icon: "Globe",
    badge: "40+ External Tools",
    enabled: true,
  },
  {
    id: "library",
    route: "/library",
    titleKey: "modules.library.title",
    descriptionKey: "modules.library.desc",
    icon: "BookOpen",
    badge: "Free Web Resources",
    enabled: true,
  },
  {
    id: "settings",
    route: "/settings",
    titleKey: "modules.settings.title",
    descriptionKey: "modules.settings.desc",
    icon: "Sliders",
    badge: "Local-First OS",
    enabled: true,
  },
];
